// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOGt4-eW63pZ7ZeQyfvaRYYeHvkwgW5bk',
    appId: '1:508490322645:android:647d201f974f83d05dc85c',
    messagingSenderId: '508490322645',
    projectId: 'messaging-6a5ad',
    storageBucket: 'messaging-6a5ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArrIIoeq2jqCXV-wUvj-E_Y3YlFm3bNOg',
    appId: '1:508490322645:ios:b2f4c385a40c48845dc85c',
    messagingSenderId: '508490322645',
    projectId: 'messaging-6a5ad',
    storageBucket: 'messaging-6a5ad.appspot.com',
    androidClientId: '508490322645-1h9t5gvkvu26fduukq8hrsk0cagb4tih.apps.googleusercontent.com',
    iosClientId: '508490322645-eglnt6fdptvte4p1g8g5thmbsb2vc98a.apps.googleusercontent.com',
    iosBundleId: 'com.example.messaging',
  );
}
